// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRuntimeState() {
  return window['go']['main']['App']['GetRuntimeState']();
}

export function PingBackend() {
  return window['go']['main']['App']['PingBackend']();
}

export function SetRequireFaceToTalk(arg1) {
  return window['go']['main']['App']['SetRequireFaceToTalk'](arg1);
}

export function StartListening() {
  return window['go']['main']['App']['StartListening']();
}

export function StopListening() {
  return window['go']['main']['App']['StopListening']();
}
