// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetRuntimeState():Promise<config.RuntimeState>;

export function PingBackend():Promise<config.BackendStatus>;

export function SetRequireFaceToTalk(arg1:boolean):Promise<config.RuntimeState>;

export function StartListening():Promise<void>;

export function StopListening():Promise<void>;
